### ISSUE TITLE
Procedures from pyxis-*.py files not loaded

### ISSUE THREAD

**Issue by matthieutrs** [ska-sa/pyxis#101]
Hello,

This issue follows the resolution of [#100](https://github.com/ska-sa/pyxis/issues/100). After building from source v.1.7.0, the procedures defined in pyxis-*.py files seem unrecognized.

More precisely, I set the pyxis-wsrt21cm.py file from the [example](https://github.com/ska-sa/pyxis/blob/master/Pyxis/doc/example/pyxis-wsrt21cm.py) in my base directory and I then run `pyxis cal_ms`. The command returns:

```
2020/07/03 15:56:11 PYXIS: ===[ Pyxis: Python eXtensions for Inteferometry Scripting (C) 2013 by Oleg Smirnov <oms@ska.ac.za> ]===
2020/07/03 15:56:11 PYXIS: VERBOSE=1 by default
2020/07/03 15:56:11 PYXIS: loading Pyxis into context '__main__'
2020/07/03 15:56:11 PYXIS: auto-loading from .: pyxis-wsrt21cm.py
2020/07/03 15:56:11 PYXIS: auto-loading from .: pyxis-wsrt21cm.py
2020/07/03 15:56:11 PYXIS: running command cal_ms
2020/07/03 15:56:11 ABORT: undefined command 'cal_ms'
2020/07/03 15:56:11 PYXIS:
2020/07/03 15:56:11 INFO: elapsed time is 0h0m0.00s
```

I don't understand:
- why we see 2 identical autoloading messages;
- the `ABORT: undefined command 'cal_ms'` message as the `cal_ms` function is indeed defined in [pyxis-wsrt21cm.py](https://github.com/ska-sa/pyxis/blob/master/Pyxis/doc/example/pyxis-wsrt21cm.py).

Would you have an idea on how to fix that?

**Comment by o-smirnov** [comment]
@matthieutrs could you please try the ``issue-101`` branch, and let me know if that fixes things? The example now runs for me.

**Comment by matthieutrs** [comment]
Thanks a lot, it is now fixed!
