### ISSUE TITLE
Fail to write log output

### ISSUE THREAD

**Issue by matthieutrs** [ska-sa/pyxis#103]
Hello,

This issue follow the resolution of [#101](https://github.com/ska-sa/pyxis/issues/101) and the building of Pyxis from source. When loading some pyxis-smh.py/pyxis-smh.conf files, I get the following error message:

```
2020/07/14 17:27:44 INFO: redirecting log output to ./log-test.txt
Traceback (most recent call last):
  File ".../software/pyxis/latest/bin/pyxis", line 45, in <module>
    from Pyxis.Commands import _info as info
  File ".../software/pyxis/latest/lib/python3.6/site-packages/Pyxis/__init__.py", line 68, in <module>
    Pyxis.Internals.initconf();
  File ".../software/pyxis/latest/lib/python3.6/site-packages/Pyxis/Internals.py", line 780, in initconf
    assign_templates();
  File ".../software/pyxis/latest/lib/python3.6/site-packages/Pyxis/Internals.py", line 683, in assign_templates
    set_logfile(Pyxis.Context.get('LOG',None));
  File ".../software/pyxis/latest/lib/python3.6/site-packages/Pyxis/Internals.py", line 739, in set_logfile
    _current_logobj = sys.stdout = sys.stderr = open(filename,mode);
ValueError: must have exactly one of create/read/write/append mode 
```

Would you have any hint on how to solve this?

**Comment by matthieutrs** [comment]
@adrianjhpc solved this by changing `mode="wa"` to `mode="a"` in [Pyxis/Internals.py](https://github.com/ska-sa/pyxis/blob/13247b8f59500445c37c83634799b2727f96bd25/Pyxis/Internals.py#L728).

**Comment by o-smirnov** [comment]
Yep, I was about to push the same change to the ``issue-101`` branch. But I'd like to sort out #102 while I'm at it...

**Comment by o-smirnov** [comment]
@matthieutrs, would you please let us know when you think all your previous scripts are working? We'll make a point release then.

**Comment by matthieutrs** [comment]
@o-smirnov we had to do 1 last change [here](https://github.com/ska-sa/pyxis/blob/4bf8c7e79f7f1cb4f3e941a40275f24dd36c408c/Pyxis/Internals.py#L790):
```Pyxis.Context[mod] = sys.modules.get(mod,sys.modules.get("Pyxides."+m));```
was replaced by
```Pyxis.Context[mod] = sys.modules.get(mod,sys.modules.get("Pyxides."+mod));```
Our installation of Pyxis from source now works like a charm!

**Comment by o-smirnov** [comment]
Ah thanks. Now that was a genuine old-time bug that moving to a new Python exposed.
