### ISSUE TITLE
Add casa 3.4 support 

### ISSUE THREAD

**Issue by Ermiasabebe** [ska-sa/pyxis#27]
Hi Folks,

The pyxis doesn't support the data reduced by CASA Version 3.4. So, can you make pyxis to support  CASA Version 3.4.0 ?

**Comment by o-smirnov** [comment]
Perhaps, but could you be a bit more specific please i.e. what is the exact problem? I.e. what commands are you running and what are the error messages?

**Comment by Ermiasabebe** [comment]
I have a kat-7 data set, which I was able to image with casa 3.4. But I'm not able to image it using pyxis; I've tried all the available imagers (casa,lwimager and wsclean). This is the error I get using casa:
```
Executing:  clean()
2015-02-25 14:44:36     SEVERE  clean::StokesImageUtil::FitGaussianPSF() (file /var/rpmbuild/BUILD/casapy420/casapy420-42.0.28322/code/synthesis/TransformMachines/StokesImageUtil.cc, line 539)        Caught Exception: NonLinearFitLM: error in loop solution
*** Error ***  No valid fits were found to PSF
leaving casapy..
```

and this from lwimager:
```
2015-02-25 14:48:32     SEVERE  SubMS::convertGridPars  Caught exception: No MeasFrame specified for conversion of Frequency
2015-02-25 14:48:32     SEVERE  SubMS::convertGridPars  Caught exception: No MeasFrame specified for conversion of Frequency
Command exited with non-zero status 1

```
You can find the data set on elwood:/home/kassaye/KAT_sources/3C147_whole_Concate.MS

**Comment by IanHeywood** [comment]
To make a CASA image, I think Pyxis will just be invoking whatever version of CASA starts when you run casapy, so I don't think this is a Pyxis bug. If lwimager and wsclean also refuse to process it then I suspect there's a problem with the Measurement Set.

I can try to take a look, but I don't have permission to access the MS.

**Comment by o-smirnov** [comment]
Yeah it's something funny with this MS. The SPECTRAL_WINDOW subtable, which contains the frequency information, lists two spectral windows with completely identical frequencies, except one is marked with a MEAS_FREQ_REF of 0, the other with 5 (these are reference codes for the different frequency reference frames). It's the 0 that makes all imagers unhappy, changing it to 5 (or imaging spw 1) makes everything work again.

Now the question is, why is the MS that way, and what are these two almost-identical spectral windows supposed to represent? @Ermiasabebe, can you investigate the origin of your MS and find out what this is supposed to be? Nadeem can probably help find out...
