### ISSUE TITLE
im.argo to combine fits and convert fits to casa images 

### ISSUE THREAD

**Issue by Ermiasabebe** [ska-sa/pyxis#35]
@SpheMakh:  I wanted to combine two or more fits files; I used the option: "pyxis
im.argo.combine_fits [fitslist,outname='combined.fits',axis=0]" since it is
 under im/argo.py. But it doesn't give me the output. For other options, like
 fits2casa (input,output) and etc, is still giving me no output. Do I miss
something ? 

I want to combine the two fits files along xaxis = 0. so I run the command in the terminal:

pyxis im.argo.combine_fits[Combined1_PKS1939.ms.channel.1ch.restored1.fits, Combined1_PKS1939.ms.channel.1ch.restored2.fits, outname=combined.fits, axis =0]

similarly, to Converts FITS image to CASA image."

pyxis im.argo.fits2casa[Combined1_PKS1939.ms.channel.1ch.restored1.fits, output= Casa_output.image]

I couldnot get the output. Perhaps, I missed something in the comand ?

**Comment by SpheMakh** [comment]
Could you describe how you want to combine the FITS files (e.g along which
axis), and include the comand that you ran.

**Comment by SpheMakh** [comment]
You added your response to your initial comment, which meant I didn't get the notification :). Ayhoo...
In the first command; you need to give the images you are combining as a list/tupple and not as separate arguments, i.e.
```
im.argo.combine_fits([fits1, fits2, fits2], outname="combined.fits", axis =0)
```
I'm not sure why im.argo.fits2casa is not working for you. Does it report an error?

**Comment by SpheMakh** [comment]
This has been fixed
