### ISSUE TITLE
update Pyxides/lsm.py for tigger-convert with intrinsic gaul support

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/pyxis#38]
Once the fix for https://github.com/ska-sa/tigger/issues/48 is merged into master, need to update lsm.py to take advantage of the new tigger-convert features:

* .gaul files are now imported automatically, and the field order is picked up from the header. No need to do kludgy stuff in pybdsm_search(), can just directly invoke tigger-convert

* can get rid of verifyGaulList() since this functionality is now available in tigger-convert as --remove-nans

**Comment by o-smirnov** [comment]
Duplicate of #60 I believe.

**Comment by SpheMakh** [comment]
Maybe lsm.py should should use PyBDSM gaul FITS output instead of the ASCII output; The FITS files have better accuracy.
