### ISSUE TITLE
lwimager: cleaning with mask seems to fail

### ISSUE THREAD

**Issue by Trienko** [ska-sa/pyxis#39]
Could someone please advise in what could be going wrong, I am trying to clean with a mask.
I have successfully called  imager.make_threshold_mask to make the mask, the mask fits file also 
exists. The imager variable is MASK_IMAGE is also set to this file. When I then call make_image it
fails saying that MAKS_IMAGE is defined. What am I doing wrong?

```
Traceback (most recent call last):
  File "/usr/local/meqtrees/pyxis/Pyxis/bin/pyxis", line 281, in <module>
    Pyxis.Internals.run(*commands);
  File "/usr/lib/python2.7/dist-packages/Pyxis/Internals.py", line 1098, in run
    comcall();
  File "./pyxis-transient.py", line 601, in burn
    make_image_with_mask(options=options,column="CORRECTED_DATA")
  File "./pyxis-transient.py", line 558, in make_image_with_mask
 imager.make_image(column=column,dirty=options,restore=options,restore_lsm=False,mask=True) # Clean with a mask
  File "/usr/lib/python2.7/dist-packages/Pyxides/imager.py", line 119, in make_image
    restoring_options=restoring_options,**kw)
  File "/usr/lib/python2.7/dist-packages/Pyxides/im/lwimager.py", line 270, in make_image
    kw['mask'] = mask = MASK_IMAGE;
NameError: global name 'MASK_IMAGE' is not defined 
```

**Comment by SpheMakh** [comment]
This looks like a bug in pyxis. However, it should only be triggered if your mask is not a FITS file. Could you post the commands that you ran, to make and use the mask?

**Comment by Trienko** [comment]
thresh = peak_flux*0.08
print "thresh = ",thresh
#mask_im is a fits file
imager.make_threshold_mask(input=mask_im,threshold=thresh) # make mask
imager.make_image(column=column,dirty=options,restore=options,restore_lsm=False,mask=True)

**Comment by Trienko** [comment]
thresh = peak_flux*0.08
print "thresh = ",thresh
#mask_im is a fits file
imager.make_threshold_mask(input=mask_im,threshold=thresh) # make mask
imager.make_image(column=column,dirty=options,restore=options,restore_lsm=False,mask=True)

**Comment by SpheMakh** [comment]
I still haven't answered Trienko :). 
you are passing a boolean as a clean mask. Try, `mask=mask_im` in 
`
imager.make_image(column=column,dirty=options,restore=options,restore_lsm=False,mask=True)
`

**Comment by Trienko** [comment]
Works...

**Comment by SpheMakh** [comment]
Cool.

**Comment by Trienko** [comment]
:-)
