### ISSUE TITLE
Absence of model, residual and psf image during interactive calibration in meqtrees

### ISSUE THREAD

**Issue by Ermiasabebe** [ska-sa/pyxis#44]
Hi all,lean

When I do calibration with meqtress interactively it will not produce the model, residual and psf images; it only produces the corrected residual or clean image when executing the "Make a clean image" button. Actually I have observed this recently. Is there something that must be adjusted ?

**Comment by o-smirnov** [comment]
No, it's a limitation of interactive mode (you can produce a psf image manually in interactive mode too). If you want all images as a matter of course, you must use pyxis.
