### ISSUE TITLE
Gain plots for XX and YY correllations 

### ISSUE THREAD

**Issue by Ermiasabebe** [ska-sa/pyxis#49]
The calibration process goes well except  warning during the plot routine (unable to get the plots). The reason, as I suspect, is the MS data has no XY and YX correlations. The error in the log is:

""""
2015/08/10 17:10:08 PYXIS: /bin/cp succeeded
2015/08/10 17:10:09 INFO: loading gain solutions from Deep-field-10s2ch-DD4/plots-Deep_field-cal-10s2ch/Deep_field-cal-10s2ch_s2.gainspw0.cp
2015/08/10 17:10:09 INFO: loaded solutions for 14 antennas
Traceback (most recent call last):
  File "/usr/local/meqtrees/Cattery/Pyxides/stefcal.py", line 173, in stefcal
    make_gain_plots(STEFCAL_GAIN_SAVE,prefix=gain_plot_prefix);
  File "/usr/local/meqtrees/Cattery/Pyxides/stefcal.py", line 668, in make_gain_plots
    gg = numpy.transpose(sols[j],(xaxis,yaxis));
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 534, in transpose
    return transpose(axes)
ValueError: axes don't match array
2015/08/10 17:10:09 WARNING: plot routine failed, see exception above

"""

Can we fix the code so as to get the Gain plots in the process ?

**Comment by o-smirnov** [comment]
Duplicates #42.
