### ISSUE TITLE
stefcal / mqt.run: DEBUG messages in terminal window

### ISSUE THREAD

**Issue by IanHeywood** [ska-sa/pyxis#50]
Running stefcal via mqt.run:

When stefcal_gain.implementation = GainDiagPhase the calibration finishes in seconds. 
When set stefcal_gain.implementation = GainDiag it takes waaaay longer and loads of DEBUG messages get dumped to the terminal.

Both cases when run via the browser finish happily in comparable times. I'm guessing the debug message logging is what's causing the hold up as these don't appear for the phase only case. Can I disable this somehow?

stefcal_verbose = 0 for both cases.

Thanks.

**Comment by o-smirnov** [comment]
That's odd -- what messages exactly? Could you paste an example please?

**Comment by IanHeywood** [comment]
I'll try to recreate the problem on my laptop. Failing that I can post the exact messages on Monday, when I will next have access to the machine it's running on.

It was [these print statements](https://github.com/ska-sa/meqtrees-cattery/blob/devel/Cattery/Calico/OMS/StefCal/StefCal.py#L683-L708) that were being triggered though.

**Comment by o-smirnov** [comment]
Ah, the dprint(0,...) ones can be safely commented out. My bad, I was chasing down a problem and left them in when I committed changes.

**Comment by IanHeywood** [comment]
OK it's gone silent but it's still slow as hell compared to phase-only and a browser run.

**Comment by IanHeywood** [comment]
Embarassing user error #42,426:

Typo on my part that was making it revert to a per time slot, per channel solution in the GainDiag case.

Status: I need a holiday.

**Comment by o-smirnov** [comment]
Well at least we killed the unnecessary debug output. :)
