### ISSUE TITLE
set thres_isl in lsm.pybdsm_search

### ISSUE THREAD

**Issue by rdeane** [ska-sa/pyxis#64]
when running `lsm.pybdsm_search(<imagename>,threshold=<somevalue>)`

the pybdsm parameter `thres_pix` is set to `<somevalue>`, however, `thres_isl` is left unchanged. Could the code be modified to specify the latter please? It's pretty important for sparse arrays (i.e. VLBI).

**Comment by SpheMakh** [comment]
You can specify any pybdsm option via lsm.pybdsm_search().
lsm.pybdsm_search(thresh_isl=<some value>) should do the trick.

**Comment by rdeane** [comment]
nope, tried that:

RuntimeError: Input parameter 'thres_isl' not recognized.

**Comment by KshitijT** [comment]
Should it not be 'thresh_isl' and not 'thres_isl'?

**Comment by rdeane** [comment]
<checks watch, notes that it's Friday afternoon>

Thanks and apologies @KshitijT and @SpheMakh

**Comment by o-smirnov** [comment]
If only it was always this easy!
