### ISSUE TITLE
Pyxides package in Cattery confuses pyxis

### ISSUE THREAD

**Issue by o-smirnov** [ska-sa/pyxis#75]
Cattery/Pyxides exists, so if a Cattery is in the ``PYTHONPATH`` before ``pyxis``, then pyxis fails to import its own Pyxides package.

Solution is to rename Cattery/Pyxides into Cattery/Pyxides-modules, and modify the pyxis import logic to scan the path for Pyxides-modules.

**Comment by o-smirnov** [comment]
Added explicit path to the standard Pyxides (taken relative to Pyxis package), this is safer. Not sure if I want to rename the Cattery one anymore, although @gijzelaerr will probably tell me off for this.

**Comment by gijzelaerr** [comment]
current state of pyxis - if it works don't touch it. So whatever is required do it, otherwise leave me out of it :P

**Comment by gijzelaerr** [comment]
i think a relative import should solve this problem 

https://docs.python.org/2.5/whatsnew/pep-328.html
