### ISSUE TITLE
Zero values for the visibilities depending on simulation time

### ISSUE THREAD

**Issue by alex-onose** [ska-sa/pyxis#78]
When using lwimager.predict_vis I am getting strange behaviour for some of the uv points.
The UV coordinates are correct but the associated predicted visibilities are set to zero.

In all simulations the first predicted visibilities are correct. Later on more and more are set to zero.
I'm not very familiar with the tools so it might just be something obvious that i'm missing.
There are no errors in the log files and everything seems to be performed successfully.

Here are some examples for the VLA for two simulations with different length in time.
![test_4](https://cloud.githubusercontent.com/assets/12749656/14212329/479e46e2-f82a-11e5-89e9-df59c7920b70.png)

![test_2_1](https://cloud.githubusercontent.com/assets/12749656/14212110/3d9e33a6-f829-11e5-8c02-995bbcbdb8f8.png)

For the second one the error for the visibilities agains values estimated in Matlab is plotted below
![test_2_2_vis_error](https://cloud.githubusercontent.com/assets/12749656/14212213/aa600b40-f829-11e5-927a-2ff89e62fb00.png)

In addition, running clean from lwimager seems to not take into account any of the points that are set to 0 by lwimager.predict_vis (even if I replace them in the MS file).
Wsclean seems to use all the points when used on the same MS file

Any help with this would be appreciated.

**Comment by o-smirnov** [comment]
Very curious, looks like lwimager is simply ignoring some MS rows (since as you say they're also not taken into account in clean). Could be a data selection issue. Please paste the logs from the relevant lwimager and wsclean invocations here.

**Comment by alex-onose** [comment]
Here are the logs:
lwimager + casa

[log-pyxis.txt](https://github.com/ska-sa/pyxis/files/208032/log.txt)
[log-simms.txt](https://github.com/ska-sa/pyxis/files/208033/log-simms.txt)

wsclean
[log-wsclean.txt](https://github.com/ska-sa/pyxis/files/208069/log-wsclean.txt)

**Comment by o-smirnov** [comment]
Odd. From the logs it does not seem like a data selection problem. 

Can you check if the missing visibilities are flagged (FLAG and FLAG_ROW columns)?

**Comment by alex-onose** [comment]
FLAG contains only zeros on all 4 columns
FLAG_ROW has some non-zero entries but not on the positions where the visibilities are set to 0.

I've attached a figure
![vis_vs_flag_row](https://cloud.githubusercontent.com/assets/12749656/14348471/93cbbc32-fcb4-11e5-84e8-087bd49e00f7.png)

**Comment by o-smirnov** [comment]
Check also the WEIGHT and WEIGHT_SPECTRUM columns.

Also, can you put the MS and the image on Dropbox or something?

**Comment by alex-onose** [comment]
The weights are all 1.
There is no WEIGHT_SPECTRUM column.

I've put the files on [dropbox](https://www.dropbox.com/s/xycju8eraz5bpp1/MS_files.zip)

**Comment by o-smirnov** [comment]
OK I think we figured this one out, it was due to CASA flagging points with elevation<0.
