### ISSUE TITLE
ms.plot_uvcov does not consider flag column

### ISSUE THREAD

**Issue by rdeane** [ska-sa/pyxis#87]
minor issue, but thought I'd post nonetheless. Try flagging half of a 24 hour run and you'll still see full uvtracks in the output figure using ```ms.plot_uvcov```

**Comment by IanHeywood** [comment]
Does the use_flags switch solve this one?

https://github.com/ska-sa/pyxis/blob/master/Pyxides/ms.py#L255

**Comment by rdeane** [comment]
Surprise, surprise - Roger didn't read the $%#&ing manual... Thanks @IanHeywood !

**Comment by IanHeywood** [comment]
> Surprise, surprise - Roger didn't read the $%#&ing manual...

Never trust anyone who does.
