### ISSUE TITLE
python3 support not working

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/pyxis#89]
A lot is still broken regarding python 3 support, primarily in the fileio handling in Internals

**Comment by gijzelaerr** [comment]
with pyxis? i never made an argo package?

**Comment by SpheMakh** [comment]
I know pyxis has an argo.py file https://github.com/ska-sa/pyxis/blob/master/Pyxides/im/argo.py, maybe that's related somehow?

**Comment by o-smirnov** [comment]
Yeah totally different argo, nothing to do with pyxis. How did it end up as a dependency?

**Comment by bennahugo** [comment]
My bad. It doesn't import in the python3 version for some reason. I'll investigate tomorrow

**Comment by bennahugo** [comment]
btw @gijzelaerr your PPA python-owlcat does not install a python3 egg, so it requires pip installing from the repository.

**Comment by gijzelaerr** [comment]
I stopped porting when I reached meqtrees-timba, that requires a lot of work to make it work. So all packages depending on timba are not python3 packaged.

It is not hard to port timba to py3, but it is hard to support py3 and py2 at the same time. I recommend making the big switch in one go, when everybody and everything is ready.

**Comment by gijzelaerr** [comment]
This depends on:

https://github.com/casacore/casacore/pull/853
https://github.com/casacore/python-casacore/pull/159

I think by now it all works properly with py3, but for py2 sometimes a unicode object slips in, and casacore doesn't support unicode fully yet. I've been wrestling with this for a while but got a bit stuck and ran out of time, and now I'm waiting for Ger to see what he can do.

The last time I checked a basic cubical run was working with both py2 and py3, but I think you astronomers need to test it more now.

**Comment by bennahugo** [comment]
Okay I also opt for saying KERN:4 will be the last deployment that supports python 2.7. The userbase (whether it is RARG/COMM/SDP can then change their dockerfiles appropriately. The distutils files should handle the python requirements, e.g. astropy 2 or latter depending on whether the user runs python 2.7 or 3

**Comment by bennahugo** [comment]
This still gives us the ability to gradually stage in python3

**Comment by gijzelaerr** [comment]
what is the status of this argo dependency? Is py3 support in pyxis still an issue?

**Comment by bennahugo** [comment]
Looks like the pyxis issues are all fixed @gijzelaerr. Only getting back onto it now, but still need to port timba, owlcat, purr, kittens and tigger-lsm. Bit of a mess to test this
